// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fgtvwbacqqudezispdgy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZndHZ3YmFjcXF1ZGV6aXNwZGd5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyODEyNzMsImV4cCI6MjA3MDg1NzI3M30.Bos9RZubbo44u8Aty8Zy4vyAdmum_iV531geFKbR9sQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});